spring.application.name=myhealthbuddy
server.port=8100
langchain4j.azure-open-ai.chat-model.endpoint=${AZURE_OPENAI_ENDPOINT}
langchain4j.azure-open-ai.chat-model.api-key=${AZURE_OPENAI_API_KEY}
langchain4j.azure-open-ai.chat-model.deployment-name=gpt-4o